FROM python:3.7
MAINTAINER Prajwal Shetty
ADD . /usr/src/app
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8080
CMD exec gunicorn your_site_name.wsgi:application --bind 0.0.0.0:8000 --workers 3